### ISSUE TITLE
Zilean indexer not working in Sonarr after update

### ISSUE THREAD

**Issue by UnbreakableKid** [dreulavelle/Prowlarr-Indexers#47] opened 2024-09-11 20:10 UTC
Updated my config with today's update, and while everything is working in Radarr and Prowlarr, Sonarr can't sync giving this error. Any idea?

Sonarr I'm using Hotio's image and I have Zilean updated

![image](https://github.com/user-attachments/assets/17f47946-8242-4ba0-b76d-98e32ed76b51)

**Comment by Pukabyte** [comment] 2024-09-12 07:34
@UnbreakableKid How did you update the indexer.yml file?

How to update custom indexers.

1. Remove indexer from Prowlarr.
2. Insert new or update existing indexer.yml file
3. Restart Prowlarr
4. Re-add indexer to Prowlarr

**Comment by UnbreakableKid** [comment] 2024-09-12 08:42
@Pukabyte I have done it like that. 

Re-did just now just to be sure by:

1. Remove indexer
2. Restart prowlarr
3. Add indexer
4. Restart prowlarr

and Sonarr is still giving issues. **Radarr and Prowlarr are fine though**.

Here are some more logs from Prowlarr. It appears that from the Sonnar query it doesn't manage to find episodes.

No one else having isses?

```
2024-09-12 09:32:47.5|Info|ReleaseSearchService|Searching indexer(s): [Zilean updated] for Term: [] for Season / Episode:[], Offset: 0, Limit: 100, Categories: [5000]
2024-09-12 09:32:47.5|Debug|Cardigann|Adding request for Zilean updated: http://zilean:8181/dmm/filtered?Query=serenity
2024-09-12 09:32:47.5|Debug|Cardigann|Downloading Feed http://zilean:8181/dmm/filtered?Query=serenity
2024-09-12 09:32:47.6|Debug|ReleaseSearchService|Total of 0 reports were found for Term: [] for Season / Episode:[], Offset: 0, Limit: 100, Categories: [5000] from 1 indexer(s)
2024-09-12 09:32:47.6|Warn|HttpClient|HTTP Error - Res: HTTP/1.1 [POST] http://sonarr:8989/api/v3/indexer: 400.BadRequest (274 bytes)
[
  {
    "isWarning": false,
    "propertyName": "",
    "errorMessage": "Query successful, but no results in the configured categories were returned from your indexer. This may be an issue with the indexer or your indexer category settings.",
    "severity": "error"
  }
]
2024-09-12 09:32:47.6|Warn|SonarrV3Proxy|No Results in configured categories. See FAQ Entry: Prowlarr will not sync X Indexer to App

[v1.23.1.4708] NzbDrone.Common.Http.HttpException: HTTP request failed: [400:BadRequest] [POST] at [http://sonarr:8989/api/v3/indexer]
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 128
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 137
   at NzbDrone.Core.Applications.Sonarr.SonarrV3Proxy.Execute[TResource](HttpRequest request) in ./Prowlarr.Core/Applications/Sonarr/SonarrV3Proxy.cs:line 214
   at NzbDrone.Core.Applications.Sonarr.SonarrV3Proxy.ExecuteIndexerRequest(HttpRequest request) in ./Prowlarr.Core/Applications/Sonarr/SonarrV3Proxy.cs:line 150
[
  {
    "isWarning": false,
    "propertyName": "",
    "errorMessage": "Query successful, but no results in the configured categories were returned from your indexer. This may be an issue with the indexer or your indexer category settings.",
    "severity": "error"
  }
]
```

Which seems weird since the logs from Zilean say they find 57 results:

```
[08:39:54] | INFO | "Zilean.ApiService.Features.Dmm.DmmEndpoints.DmmFilteredInstance" | Performing filtered search for DmmFilteredRequest { Query: "serenity", Season: null, Episode: null, Year: null,
Language: null, Resolution: null, ImdbId: null }
[08:39:54] | INFO | "Zilean.ApiService.Features.Dmm.DmmEndpoints.DmmFilteredInstance" | Filtered search for "serenity" returned 57 results
```

But in Prowlarr manual search:

![image](https://github.com/user-attachments/assets/c0a4d3a6-da07-4c5b-b9e4-3c095f7f60d8)

**Comment by Pukabyte** [comment] 2024-09-13 05:21
Give it another go with the pull request. The issue is the default search for "serenity" not returning any results for tv shows. I have changed it to limitless and can confirm it now works with sonarr

**Comment by Pukabyte** [comment] 2024-09-13 07:56
@UnbreakableKid It has been merged with latest

**Comment by Pukabyte** [comment] 2024-09-13 07:56
Fixed

**Closed** 2024-09-13 07:56 UTC
